// Generated by gencpp from file my_server/add_two_ints.msg
// DO NOT EDIT!


#ifndef MY_SERVER_MESSAGE_ADD_TWO_INTS_H
#define MY_SERVER_MESSAGE_ADD_TWO_INTS_H

#include <ros/service_traits.h>


#include <my_server/add_two_intsRequest.h>
#include <my_server/add_two_intsResponse.h>


namespace my_server
{

struct add_two_ints
{

typedef add_two_intsRequest Request;
typedef add_two_intsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct add_two_ints
} // namespace my_server


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_server::add_two_ints > {
  static const char* value()
  {
    return "f0b6d69ea10b0cf210cb349d58d59e8f";
  }

  static const char* value(const ::my_server::add_two_ints&) { return value(); }
};

template<>
struct DataType< ::my_server::add_two_ints > {
  static const char* value()
  {
    return "my_server/add_two_ints";
  }

  static const char* value(const ::my_server::add_two_ints&) { return value(); }
};


// service_traits::MD5Sum< ::my_server::add_two_intsRequest> should match
// service_traits::MD5Sum< ::my_server::add_two_ints >
template<>
struct MD5Sum< ::my_server::add_two_intsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_server::add_two_ints >::value();
  }
  static const char* value(const ::my_server::add_two_intsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_server::add_two_intsRequest> should match
// service_traits::DataType< ::my_server::add_two_ints >
template<>
struct DataType< ::my_server::add_two_intsRequest>
{
  static const char* value()
  {
    return DataType< ::my_server::add_two_ints >::value();
  }
  static const char* value(const ::my_server::add_two_intsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_server::add_two_intsResponse> should match
// service_traits::MD5Sum< ::my_server::add_two_ints >
template<>
struct MD5Sum< ::my_server::add_two_intsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_server::add_two_ints >::value();
  }
  static const char* value(const ::my_server::add_two_intsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_server::add_two_intsResponse> should match
// service_traits::DataType< ::my_server::add_two_ints >
template<>
struct DataType< ::my_server::add_two_intsResponse>
{
  static const char* value()
  {
    return DataType< ::my_server::add_two_ints >::value();
  }
  static const char* value(const ::my_server::add_two_intsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_SERVER_MESSAGE_ADD_TWO_INTS_H
